version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
  server:
    build: ./server
    restart: always
    depends_on: 
      - mysql
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - RP_PORT=8001
      - MYSQLHOST=mysql
      - MYSQLUSER=root
      - MYSQLPASS=example
    volumes:
      - ./server/backend:/app/backend
      - ./server/frontend:/app/frontend
      - ./server/reverse_proxy:/app/reverse_proxy
    ports:
      - "8001:8001"